import Head from 'next/head';
import Header from '../../components/Header';
import Navigation from '../../components/Navigation';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600"
          rel="stylesheet"
        />
      </head>

      <body className="bg-secondary mx-auto">
        <Header />
        {/* <Navigation /> */}
        {children}
      </body>
    </html>
  );
}
